// <auto-generated />
using System;
using Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220316152430_seederDestbank")]
    partial class seederDestbank
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DataTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInstallmentAllowed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Paid")
                        .HasColumnType("numeric");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Data.Entities.Otp", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DataTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Sessions")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("Data.Entities.Partner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DataTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IPNUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternalPrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternalPublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartnerPublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Data.Entities.Payment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CurrencyUnit")
                        .HasColumnType("text");

                    b.Property<string>("DataTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IPNUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentReferenceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReturnUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceReferenceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Data.Entities.PaymentDestination", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DataTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartnerId")
                        .HasColumnType("text");

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.Property<int>("TimeoutAfterMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PaymentDestionations");

                    b.HasData(
                        new
                        {
                            Id = "ATM",
                            DataTransactionId = "",
                            ExternalId = "ATM",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806135041944131ABBANK.svg",
                            IsDeleted = false,
                            Name = "ATM nội địa",
                            OtherName = "",
                            ParentId = "",
                            PartnerId = "",
                            SortIndex = 1,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_ABBANK",
                            DataTransactionId = "",
                            ExternalId = "ABBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806135041944131ABBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng thương mại cổ phần An Bình (ABBANK)",
                            OtherName = "ABBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 2,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_ACB",
                            DataTransactionId = "",
                            ExternalId = "ACB",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806135845873936ACB_Logo.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng thương mại cổ phần An Bình (ABBANK)",
                            OtherName = "ACB",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 3,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_AGRIBANK",
                            DataTransactionId = "",
                            ExternalId = "AGRIBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806136353202179ARIBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Nông nghiệp(Agribank)",
                            OtherName = "AGRIBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 4,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_BACABANK",
                            DataTransactionId = "",
                            ExternalId = "BACABANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806137216146940BACABANK.svg",
                            IsDeleted = false,
                            Name = "Ngân Hàng TMCP Bắc Á",
                            OtherName = "BACABANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 5,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_BIDV",
                            DataTransactionId = "",
                            ExternalId = "BIDV",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806145503628415BIDV.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng đầu tư và phát triển Việt Nam (BIDV)",
                            OtherName = "BIDV",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 6,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_DONGABANK",
                            DataTransactionId = "",
                            ExternalId = "DONGABANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806146169753496DONGABANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Đông Á (DongABank)",
                            OtherName = "DONGABANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 7,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_EXIMBANK",
                            DataTransactionId = "",
                            ExternalId = "EXIMBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806146480725517EXIMBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng EximBank",
                            OtherName = "EXIMBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 8,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_HDBANK",
                            DataTransactionId = "",
                            ExternalId = "HDBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806146835748104HDBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng HDBank",
                            OtherName = "HDBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 9,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_IVB",
                            DataTransactionId = "",
                            ExternalId = "IVB",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806147771348722IVB.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng TNHH Indovina (IVB)",
                            OtherName = "IVB",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 10,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_MBBANK",
                            DataTransactionId = "",
                            ExternalId = "MBBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806148334174391MBBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng thương mại cổ phần Quân đội",
                            OtherName = "MBBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 11,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_MSBANK",
                            DataTransactionId = "",
                            ExternalId = "MSBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806148722740319MSBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Hàng Hải (MSBANK)",
                            OtherName = "MSBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 12,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_NAMABANK",
                            DataTransactionId = "",
                            ExternalId = "NAMABANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806149034305829NAMABANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Nam Á (NamABank)",
                            OtherName = "NAMABANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 13,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_NCB",
                            DataTransactionId = "",
                            ExternalId = "NCB",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806149392457643NCB.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Quốc dân (NCB)",
                            OtherName = "NCB",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 14,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_OCB",
                            DataTransactionId = "",
                            ExternalId = "OCB",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806149720383917OCB.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Phương Đông (OCB)",
                            OtherName = "OCB",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 15,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_OJB",
                            DataTransactionId = "",
                            ExternalId = "OJB",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806150185376395OJB.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Đại Dương (OceanBank)",
                            OtherName = "OJB",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 16,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_PVCOMBANK",
                            DataTransactionId = "",
                            ExternalId = "PVCOMBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806150584043429PVCOMBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng TMCP Đại Chúng Việt Nam",
                            OtherName = "PVCOMBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 17,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_SACOMBANK",
                            DataTransactionId = "",
                            ExternalId = "SACOMBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806150961847582SACOMBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng TMCP Sài Gòn Thương Tín (SacomBank)",
                            OtherName = "SACOMBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 18,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_SAIGONBANK",
                            DataTransactionId = "",
                            ExternalId = "SAIGONBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806151334395650SAIGONBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng thương mại cổ phần Sài Gòn Công Thương",
                            OtherName = "SAIGONBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 19,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_SCB",
                            DataTransactionId = "",
                            ExternalId = "SCB",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806151750966277SCB.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng TMCP Sài Gòn (SCB)",
                            OtherName = "SCB",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 20,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_SHB",
                            DataTransactionId = "",
                            ExternalId = "SHB",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806152081167626SHB.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Thương mại cổ phần Sài Gòn - Hà Nội(SHB)",
                            OtherName = "SHB",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 21,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_TECHCOMBANK",
                            DataTransactionId = "",
                            ExternalId = "TECHCOMBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806152434991789TECHCOMBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Kỹ thương Việt Nam (TechcomBank)",
                            OtherName = "TECHCOMBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 22,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_TPBANK",
                            DataTransactionId = "",
                            ExternalId = "TPBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806152821982180TPBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Tiên Phong (TPBank)",
                            OtherName = "TPBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 23,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VPBANK",
                            DataTransactionId = "",
                            ExternalId = "VPBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806153176785902VPBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Việt Nam Thịnh vượng (VPBank)",
                            OtherName = "VPBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 24,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_SEABANK",
                            DataTransactionId = "",
                            ExternalId = "SEABANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806153613863188SEABANK.svg",
                            IsDeleted = false,
                            Name = "Ngân Hàng TMCP Đông Nam Á",
                            OtherName = "SEABANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 25,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VIB",
                            DataTransactionId = "",
                            ExternalId = "VIB",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806154064036274VIB.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Thương mại cổ phần Quốc tế Việt Nam (VIB)",
                            OtherName = "VIB",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 26,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VIETABANK",
                            DataTransactionId = "",
                            ExternalId = "VIETABANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806154670860918VIETABANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng TMCP Việt Á",
                            OtherName = "VIETABANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 27,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VIETBANK",
                            DataTransactionId = "",
                            ExternalId = "VIETBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806154976980402VIETBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng thương mại cổ phần Việt Nam Thương Tín",
                            OtherName = "VIETBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 28,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VIETCAPITALBANK",
                            DataTransactionId = "",
                            ExternalId = "VIETCAPITALBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806155803081396VIETCAPITALBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân Hàng Bản Việt",
                            OtherName = "VIETCAPITALBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 29,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VIETCOMBANK",
                            DataTransactionId = "",
                            ExternalId = "VIETCOMBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806156140837146VIETCOMBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Ngoại thương (Vietcombank)",
                            OtherName = "VIETCOMBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 30,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VIETINBANK",
                            DataTransactionId = "",
                            ExternalId = "VIETINBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806156538841413VIETINBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng Công thương (Vietinbank)",
                            OtherName = "VIETINBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 31,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_BIDC",
                            DataTransactionId = "",
                            ExternalId = "BIDC",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806157091593789BIDC.svg",
                            IsDeleted = false,
                            Name = "Ngân Hàng BIDC",
                            OtherName = "BIDC",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 32,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_LAOVIETBANK",
                            DataTransactionId = "",
                            ExternalId = "LAOVIETBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806157407385460LAOVIETBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng liên doanh Việt - Lào",
                            OtherName = "LAOVIETBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 28,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_WOORIBANK",
                            DataTransactionId = "",
                            ExternalId = "WOORIBANK",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806157725268942WOORIBANK.svg",
                            IsDeleted = false,
                            Name = "Ngân hàng TNHH MTV Woori Việt Nam",
                            OtherName = "WOORIBANK",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 29,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_AMEX",
                            DataTransactionId = "",
                            ExternalId = "AMEX",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806158590292143AMEX.svg",
                            IsDeleted = false,
                            Name = "American Express",
                            OtherName = "AMEX",
                            ParentId = "ATM",
                            PartnerId = "VnPay",
                            SortIndex = 30,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VISAMASTERCARD",
                            DataTransactionId = "",
                            ExternalId = "VISAMASTERCARD",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806788995070189VISAA.svg",
                            IsDeleted = false,
                            Name = "Thẻ VISA/MasterCard",
                            OtherName = "",
                            ParentId = "",
                            PartnerId = "VnPay",
                            SortIndex = 31,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VISA",
                            DataTransactionId = "",
                            ExternalId = "VISA",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806159138178191VISA.svg",
                            IsDeleted = false,
                            Name = "Thẻ quốc tế Visa",
                            OtherName = "VISA",
                            ParentId = "VISAMASTERCARD",
                            PartnerId = "VnPay",
                            SortIndex = 32,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_MASTERCARD",
                            DataTransactionId = "",
                            ExternalId = "MASTERCARD",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806159568096097MASTERCARD.svg",
                            IsDeleted = false,
                            Name = "Thẻ quốc tế MasterCard",
                            OtherName = "MASTERCARD",
                            ParentId = "VISAMASTERCARD",
                            PartnerId = "VnPay",
                            SortIndex = 33,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_JCB",
                            DataTransactionId = "",
                            ExternalId = "JCB",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806159890256198JCB.svg",
                            IsDeleted = false,
                            Name = "Thẻ quốc tế JCB",
                            OtherName = "VIETBANK",
                            ParentId = "VISAMASTERCARD",
                            PartnerId = "VnPay",
                            SortIndex = 34,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_UPI",
                            DataTransactionId = "",
                            ExternalId = "UPI",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806160185997487UPI.svg",
                            IsDeleted = false,
                            Name = "UnionPay International",
                            OtherName = "UPI",
                            ParentId = "VISAMASTERCARD",
                            PartnerId = "VnPay",
                            SortIndex = 35,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "WALLET",
                            DataTransactionId = "",
                            ExternalId = "WALLET",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806787010871969VDT.svg",
                            IsDeleted = false,
                            Name = "Ví điện tử",
                            OtherName = "WALLET",
                            ParentId = "",
                            PartnerId = "",
                            SortIndex = 36,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VNMART",
                            DataTransactionId = "",
                            ExternalId = "VNMART",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806160926622446VNMART.svg",
                            IsDeleted = false,
                            Name = "Ví điện tử VnMart",
                            OtherName = "VNMART",
                            ParentId = "WALLET",
                            PartnerId = "VnPay",
                            SortIndex = 37,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VNPAYQR",
                            DataTransactionId = "",
                            ExternalId = "VNPAYQR",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806161202568121VNPAYQR.svg",
                            IsDeleted = false,
                            Name = "Cổng thanh toán VNPAYQR",
                            OtherName = "VNPAYQR",
                            ParentId = "WALLET",
                            PartnerId = "VnPay",
                            SortIndex = 38,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_1PAY",
                            DataTransactionId = "",
                            ExternalId = "1PAY",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/6378061615550260751PAY.svg",
                            IsDeleted = false,
                            Name = "Ví điện tử 1Pay",
                            OtherName = "1PAY",
                            ParentId = "WALLET",
                            PartnerId = "VnPay",
                            SortIndex = 39,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_FOXPAY",
                            DataTransactionId = "",
                            ExternalId = "FOXPAY",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806162211903212FOXPAY.svg",
                            IsDeleted = false,
                            Name = "Ví điện tử FOXPAY",
                            OtherName = "FOXPAY",
                            ParentId = "WALLET",
                            PartnerId = "VnPay",
                            SortIndex = 40,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VIMASS",
                            DataTransactionId = "",
                            ExternalId = "VIMASS",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806162551187494VIMASS.svg",
                            IsDeleted = false,
                            Name = "Ví điện tử Vimass",
                            OtherName = "VIMASS",
                            ParentId = "WALLET",
                            PartnerId = "VnPay",
                            SortIndex = 41,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VINID",
                            DataTransactionId = "",
                            ExternalId = "VINID",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806162971967373VINID.svg",
                            IsDeleted = false,
                            Name = "Ví điện tử VINID",
                            OtherName = "VINID",
                            ParentId = "WALLET",
                            PartnerId = "VnPay",
                            SortIndex = 42,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VIVIET",
                            DataTransactionId = "",
                            ExternalId = "VIVIET",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806163321063446VIVIET.svg",
                            IsDeleted = false,
                            Name = "Ví điện tử Ví Việt",
                            OtherName = "VIVIET",
                            ParentId = "WALLET",
                            PartnerId = "VnPay",
                            SortIndex = 43,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VNPTPAY",
                            DataTransactionId = "",
                            ExternalId = "VNPTPAY",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806163623465015VNPTPAY.svg",
                            IsDeleted = false,
                            Name = "Ví điện tử VNPTPAY",
                            OtherName = "VNPTPAY",
                            ParentId = "WALLET",
                            PartnerId = "VnPay",
                            SortIndex = 44,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_YOLO",
                            DataTransactionId = "",
                            ExternalId = "YOLO",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806163905567330YOLO.svg",
                            IsDeleted = false,
                            Name = "Ví điện tử YOLO",
                            OtherName = "YOLO",
                            ParentId = "WALLET",
                            PartnerId = "VnPay",
                            SortIndex = 45,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_VNPAYWallet",
                            DataTransactionId = "",
                            ExternalId = "VNPAYWallet",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806630257309056VNPayWallet.svg",
                            IsDeleted = false,
                            Name = "Ví điện tử VNPay",
                            OtherName = "VNPAYWallet",
                            ParentId = "WALLET",
                            PartnerId = "VnPay",
                            SortIndex = 47,
                            TimeoutAfterMinutes = 0
                        },
                        new
                        {
                            Id = "VnPay_captureWallet",
                            DataTransactionId = "",
                            ExternalId = "captureWallet",
                            Group = "",
                            Image = "https://s3.cloud.cmctelecom.vn/bank/637806628704496660MomoWallet.svg",
                            IsDeleted = false,
                            Name = "Ví điện tử MoMo",
                            OtherName = "captureWallet",
                            ParentId = "WALLET",
                            PartnerId = "MOMO",
                            SortIndex = 46,
                            TimeoutAfterMinutes = 0
                        });
                });

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PartnerId")
                        .HasColumnType("text");

                    b.Property<string>("PartnerKey")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Data.Entities.UserToken", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DataTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirebaseToken")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("TokenValue")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
